# Deep Neural Networks with TensorFlow
- Course: Self Driving Car Nanodegree
- Lesson 6: Intro to TensorFlow
- Lesson 7: Deep Neural Netwoks
- Topic: Math and other operations for Neural Networks with TF

### Variables and variable initialization
tf.constant() and tf.placeholder() instantiate tensors which can not be modified. For modifiable tensors, the used class is **tf.Variable**.

The **tf.global_variables_initializer()** funcion initializes the state of all variable tensors.

In [6]:
import tensorflow as tf

x = tf.Variable(5) # 5 is defined as initial value
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    getX = sess.run(x)
    print(getX)

5


### Weights init with randon numbers from normal distribution
For the case of variables initialization, in this case the weights matrix, with randon numbers on normal distribution, TF provides the function: **tf.truncated_normal()**

In [15]:
import tensorflow as tf

n_features = 3
n_labels = 2
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
bias = tf.Variable(tf.zeros(n_labels))

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    getW = sess.run(weights)
    print("Weights")
    print(getW)
    getB = sess.run(bias)
    print("Bias")
    print(getB)

Weights
[[-1.23768318 -1.14573717]
 [ 0.46240932 -0.19823064]
 [-0.23971376 -1.10599101]]
Bias
[ 0.  0.]


### Softmax with Numpy

In [22]:
# Solution is available in the other "solution.py" tab
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    # TODO: Compute and return softmax(x)
    eX = np.exp(x)
    sumX = np.sum((eX), axis=0)
    # other solution:
    # return np.exp(x) / np.sum(np.exp(x), axis=0)
    return eX/sumX

logits = [3.0, 1.0, 2.0]
print(softmax(logits))

[ 0.66524096  0.09003057  0.24472847]


### Softmax in TensorFlow
TF provides a softmax implementation: **tf.nn.softmax()**

In [23]:
import tensorflow as tf

def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)
    
    with tf.Session() as sess:
        # TODO: Feed in the logit data
        output = sess.run(softmax, feed_dict={logits:logit_data} )

    return output

print(run())

[ 0.65900117  0.24243298  0.09856589]


### One-Hot Encoding and Cross entropy evaluation
The output probability from softmax can be evaluated against One-Hot Encoding vectors through a Cross entropy function. This value can be used as loss or cost to measure how well the model classifies the correct lable (high probability for the right label and low probability for the other labels).

Cross entropy evaluation at TF is done with the help from **tf.reduce_sum()**, which sums all elements at an array and **tf.log()**.

    Cross entropy function: D
    Softmax output array: S
    One hot enconded labels: L
    D(S,L) = -sum(Li * log(Si))

In [38]:
import tensorflow as tf

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# TODO: Print cross entropy from session
D = -tf.reduce_sum(one_hot * tf.log(softmax))
with tf.Session() as sess:
    print("Cross A: ", sess.run(D, feed_dict={softmax:softmax_data, one_hot:one_hot_data}))
    

Cross A:  0.356675


### Mini-batch feature selection
One technique to reduce the input size is to use mini-batch. The implementation of variable size arrays (mini-batch with variable size) is done with **None**:
   
    features = tf.placeholder(tf.float32, [None, n_input])
    labels = tf.placeholder(tf.float32, [None, n_classes])

In [46]:
import tensorflow as tf
from pprint import pprint

def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
    # pass
    output_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        output_batches.append(batch)
    return output_batches

# 4 Samples of features
example_features = [
    ['F11','F12','F13','F14'],
    ['F21','F22','F23','F24'],
    ['F31','F32','F33','F34'],
    ['F41','F42','F43','F44']]
# 4 Samples of labels
example_labels = [
    ['L11','L12'],
    ['L21','L22'],
    ['L31','L32'],
    ['L41','L42']]

# PPrint prints data structures like 2d arrays, so they are easier to read
outputb = batches(3, example_features, example_labels)
for b_f, b_l in outputb:
    print(b_f)
    print("--")
    print(b_l)

[['F11', 'F12', 'F13', 'F14'], ['F21', 'F22', 'F23', 'F24'], ['F31', 'F32', 'F33', 'F34']]
--
[['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]
[['F41', 'F42', 'F43', 'F44']]
--
[['L41', 'L42']]


### Rectified Linear Unit - ReLU
The introduction of non-linear layers allows the NN to solve more complex problems besides linear models. One option to non-linear layers are ReLUs:

    f(x) = max(0,x)

This funcion in TF is represented as **tf.nn.relu()**. The code snippet below shows the implementation of the the followin network: 
    
    |Linear Op| -> |ReLU| -> |Linear Op(Output)|

In [ ]:
# Code snippet 
# Hidden Layer with ReLU activation function
hidden_layer = tf.add(tf.matmul(features, hidden_weights), hidden_biases)
hidden_layer = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_layer, output_weights), output_biases)

In [5]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model
hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)
output_layer = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])

# TODO: Print session results
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(output_layer))

[[  5.11000013   8.44000053]
 [  0.           0.        ]
 [ 24.01000214  38.23999786]]


### Save and Restore models
Saving and restoring operations are necessary since models can take quite long to train and allow it to latter use also. TF supports saving any **tf.Variable** with the method **tf.train.Saver.save()**

In [27]:
import tensorflow as tf

tf.reset_default_graph()

save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]), name='weights_0')
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Save Weights: {}'.format(weights.name))
print('Save Bias: {}'.format(bias.name))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Show the values of weights and bias
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))
    saver.save(sess, save_file)

Save Weights: weights_0:0
Save Bias: bias_0:0
Weights:
[[ 0.21265516 -0.97449255  0.1696125 ]
 [-1.7415607  -1.06699133 -1.14284909]]
Bias:
[-0.26254612 -0.77674264 -0.25262544]


### Restore model
The same TF class also holds the method to restore models **tf.train.Saver.restore()**

In [28]:
# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')
weights = tf.Variable(tf.truncated_normal([2, 3]) ,name='weights_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Load Weights: {}'.format(weights.name))
print('Load Bias: {}'.format(bias.name))

with tf.Session() as sess:
    # Load the weights and bias - No Error
    saver.restore(sess, save_file)
    # Show the values of weights and bias
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))
    
print('Loaded Weights and Bias successfully.')

Load Weights: weights_0:0
Load Bias: bias_0:0
Weight:
[[ 0.21265516 -0.97449255  0.1696125 ]
 [-1.7415607  -1.06699133 -1.14284909]]
Bias:
[-0.26254612 -0.77674264 -0.25262544]
Loaded Weights and Bias successfully.


### Dropout technique
The TF library supports the dropout technique through the method **tf.nn.dropout()**. This method takes two input params: layer to apply the dropout technique and the probability to keep a node (not dropping). See the code snippet below for implementation example.

- For **training**, a good start probability number to keep a node is **0,5**.
- For **testing** however, it's better to use the whole model, hence a probability to keep a node of **1,0**.

In [ ]:
keep_prob = tf.placeholder(tf.float32) # probability to keep units

hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)
hidden_layer = tf.nn.dropout(hidden_layer, keep_prob)

logits = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])

### B